#!/bin/bash

WALLPAPERS_DIR="$HOME/Downloads/Backgrounds-home/
ROFI_THEME="$HOME/.config/rofi/wallpaper_changer.rasi" # Rofi theme for the changer menu

if ! pgrep -x hyprpaper > /dev/null; then
    hyprpaper &
fi

WALLPAPER_LIST=$(find "$WALLPAPERS_DIR" -type f -regex ".*\(jpg\|jpeg\|png\)" -print0 | xargs -0 basename -a)

chosen_wallpaper=$(echo -e "$WALLPAPER_LIST" | rofi -dmenu -i -p "Wallpapers" -theme "$ROFI_THEME")

if [ -n "$chosen_wallpaper" ]; then
    FULL_WALLPAPER_PATH="$WALLPAPERS_DIR/$chosen_wallpaper"

    wal -i "$FULL_WALLPAPER_PATH"

    hyprctl hyprpaper preload "$FULL_WALLPAPER_PATH"
    hyprctl hyprpaper wallpaper ",$FULL_WALLPAPER_PATH" # Sets it for all monitors

    killall waybar && waybar &

fi
